branch-defaults:
  default:
    environment: spring-boot-demo-dev
    group_suffix: null
  main:
    environment: spring-boot-demo-dev
    group_suffix: null
deploy:
  artifact: target/demo-0.0.1-SNAPSHOT.jar
global:
  application_name: spring-boot-demo
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
